# Generated by Django 4.2.1 on 2023-05-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='picture',
            field=models.ImageField(height_field='height', max_length=1024, null=True, upload_to='', width_field='width'),
        ),
    ]
